// generated by diplomat-tool
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class FinalizerOrderDependent {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    readsSource(): boolean;
}