// generated by diplomat-tool
import { FinalizerOrderDependent } from "./FinalizerOrderDependent.mjs"
import wasm from "./diplomat-wasm.mjs";
import * as diplomatRuntime from "./diplomat-runtime.mjs";

const FinalizerOrderSource_box_destroy_registry = new FinalizationRegistry((ptr) => {
    wasm.FinalizerOrderSource_destroy(ptr);
});

export class FinalizerOrderSource {
    // Internal ptr reference:
    #ptr = null;

    // Lifetimes are only to keep dependencies alive.
    // Since JS won't garbage collect until there are no incoming edges.
    #selfEdge = [];

    #internalConstructor(symbol, ptr, selfEdge) {
        if (symbol !== diplomatRuntime.internalConstructor) {
            console.error("FinalizerOrderSource is an Opaque type. You cannot call its constructor.");
            return;
        }
        this.#ptr = ptr;
        this.#selfEdge = selfEdge;

        // Are we being borrowed? If not, we can register.
        if (this.#selfEdge.length === 0) {
            FinalizerOrderSource_box_destroy_registry.register(this, this.#ptr);
        }

        return this;
    }
    /** @internal */
    get ffiValue() {
        return this.#ptr;
    }


    static create() {

        const result = wasm.FinalizerOrderSource_create();

        try {
            return new FinalizerOrderSource(diplomatRuntime.internalConstructor, result, []);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    makeDependent() {
        // This lifetime edge depends on lifetimes 'a
        let aEdges = [this];


        const result = wasm.FinalizerOrderSource_make_dependent(this.ffiValue);

        try {
            return new FinalizerOrderDependent(diplomatRuntime.internalConstructor, result, [], aEdges);
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    static resetProbe() {
    wasm.FinalizerOrderSource_reset_probe();

        try {}

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    static sourceDrops() {

        const result = wasm.FinalizerOrderSource_source_drops();

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    static dependentDrops() {

        const result = wasm.FinalizerOrderSource_dependent_drops();

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    static badOrderDrops() {

        const result = wasm.FinalizerOrderSource_bad_order_drops();

        try {
            return result;
        }

        finally {
            diplomatRuntime.FUNCTION_PARAM_ALLOC.clean();
        }
    }

    constructor(symbol, ptr, selfEdge) {
        return this.#internalConstructor(...arguments)
    }
}