// generated by diplomat-tool
import type { FinalizerOrderDependent } from "./FinalizerOrderDependent"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



export class FinalizerOrderSource {
    /** @internal */
    get ffiValue(): pointer;
    /** @internal */
    constructor();


    static create(): FinalizerOrderSource;

    makeDependent(): FinalizerOrderDependent;

    static resetProbe(): void;

    static sourceDrops(): bigint;

    static dependentDrops(): bigint;

    static badOrderDrops(): bigint;
}